#!/usr/bin/env bash
. ../virtuoso_fct.sh --source-only
limit=500000;

resp_interlang=$(run_virtuoso_cmd "SPARQL \
SELECT count(?s) FROM <http://fr.dbpedia.org/graph/dbpedia_generic_geo-coordinates> WHERE {\
?s ?p ?o \
};");

 
CONSTRUCT {
?s dbo:relatedPlaces [
 ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type.
 ?s <http://www.georss.org/georss/point> ?point.
 ?s <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?lat.
 ?s <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?long.
?s <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> ?geo.
]
} WHERE {
SELECT ?s ?p ?o FROM <http://fr.dbpedia.org/graph/dbpedia_generic_geo-coordinates> WHERE {
?s ?p ?o.
OPTIONAL{ ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type ;}
OPTIONAL{ ?s <http://www.georss.org/georss/point> ?point ;}
OPTIONAL { ?s <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?lat;}
OPTIONAL { ?s <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?long;}
OPTIONAL { ?s <http://www.w3.org/2003/01/geo/wgs84_pos#geometry> ?geo;}
} LIMIT 500
} 


