#!/usr/bin/env bash
. ../virtuoso_fct.sh --source-only

################### SPARQL - GET LANG LIST
get_lang_labels="SPARQL \
SELECT DISTINCT ?lang FROM <http://fr.dbpedia.org/graph/dbpedia_generic_labels> where {\
?s rdfs:label ?o.\
BIND (lang(?o) AS ?lang)\
}";
resp=$(run_virtuoso_cmd "$get_lang_labels");
lang_list=$(echo $resp | tr " " "\n");
for lang in ${lang_list[@]}; do
  echo "$lang need to be treaten";
done
